---
# tasks file for common
- name: Download and install RKE2
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL="{{ rke2_channel }}" INSTALL_RKE2_VERSION="{{ rke2_version }}" sh -
  args:
    creates: /usr/local/bin/rke2
